import { useState, useEffect } from 'react';
import API from '../api';

export default function Receipts() {
  const [view, setView] = useState('list');
  const [movements, setMovements] = useState([]);
  const [products, setProducts] = useState([]);
  const [locations, setLocations] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [alert, setAlert] = useState(null);
  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [validating, setValidating] = useState(false);
  const [form, setForm] = useState({ supplier_id: '', scheduleDate: '', to_location: '', lines: [{ product_id: '', quantity: '' }] });

  const receipts = movements.filter(m => m.operation_type === 'receipt');
  const filtered = receipts.filter(m => {
    const matchSearch = !search || m.reference?.toLowerCase().includes(search.toLowerCase()) || m.product_name?.toLowerCase().includes(search.toLowerCase());
    return matchSearch;
  });

  const loadAll = () => {
    setLoading(true);
    API.get('/stock-movements').then(r => setMovements(r.data.movements || [])).finally(() => setLoading(false));
  };

  useEffect(() => {
    loadAll();
    API.get('/products').then(r => setProducts(r.data.products || []));
    API.get('/suppliers').then(r => setSuppliers(r.data.suppliers || []));
    API.get('/warehouses/all-locations').then(r => setLocations(r.data.locations || []));
  }, []);

  const showAlert = (msg, type = 'success') => { setAlert({ msg, type }); setTimeout(() => setAlert(null), 4000); };

  const addLine = () => setForm({ ...form, lines: [...form.lines, { product_id: '', quantity: '' }] });
  const removeLine = (i) => { if (form.lines.length === 1) return; setForm({ ...form, lines: form.lines.filter((_, idx) => idx !== i) }); };
  const updateLine = (i, field, val) => { const lines = [...form.lines]; lines[i] = { ...lines[i], [field]: val }; setForm({ ...form, lines }); };

  const refNum = `WH/IN/${String(receipts.length + 1).padStart(4, '0')}`;
  const totalQty = form.lines.reduce((sum, l) => sum + (Number(l.quantity) || 0), 0);
  const validLines = form.lines.filter(l => l.product_id && l.quantity);

  const handleValidate = async () => {
    if (!form.to_location) { showAlert('Please select a destination location', 'error'); return; }
    if (validLines.length === 0) { showAlert('Please add at least one product', 'error'); return; }
    setValidating(true);
    try {
      for (const line of validLines) {
        await API.post('/stock-movements', {
          product_id: Number(line.product_id),
          quantity: Number(line.quantity),
          operation_type: 'receipt',
          to_location: Number(form.to_location),
          from_location: null,
          reference: refNum,
          supplier_id: form.supplier_id ? Number(form.supplier_id) : undefined,
        });
      }
      showAlert(`Receipt ${refNum} validated ✅ — ${totalQty} units added to stock`);
      setView('list');
      setForm({ supplier_id: '', scheduleDate: '', to_location: '', lines: [{ product_id: '', quantity: '' }] });
      loadAll();
    } catch (err) {
      showAlert(err.response?.data?.message || 'Validation failed', 'error');
    }
    setValidating(false);
  };

  const handlePrint = () => {
    const supplierName = suppliers.find(s => s.id === Number(form.supplier_id))?.name || 'N/A';
    const destLocation = locations.find(l => l.id === Number(form.to_location));
    const w = window.open('', '_blank');
    w.document.write(`
      <html><head><title>Receipt ${refNum}</title>
      <style>body{font-family:monospace;padding:30px;max-width:600px;margin:0 auto}h1{font-size:18px;margin-bottom:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:8px;text-align:left}th{background:#f5f5f5}.footer{margin-top:30px;font-size:12px;color:#666}</style>
      </head><body>
      <h1>STOCK RECEIPT: ${refNum}</h1>
      <p><b>Supplier:</b> ${supplierName}</p>
      <p><b>Destination:</b> ${destLocation ? `${destLocation.warehouse_name} — ${destLocation.name}` : 'N/A'}</p>
      <p><b>Date:</b> ${form.scheduleDate || new Date().toLocaleDateString()}</p>
      <br/>
      <table><tr><th>Product</th><th>SKU</th><th>Quantity</th></tr>
      ${validLines.map(l => { const p = products.find(p => p.id === Number(l.product_id)); return `<tr><td>${p?.name||''}</td><td>${p?.sku||''}</td><td>${l.quantity} ${p?.unit_of_measure||'units'}</td></tr>`; }).join('')}
      </table>
      <p><b>Total Units:</b> ${totalQty}</p>
      <div class="footer">Generated by CoreInventory · ${new Date().toLocaleString()}</div>
      </body></html>`);
    w.document.close();
    w.print();
  };

  if (view === 'new') return (
    <div style={{ animation: 'pageEnter 0.3s ease' }}>
      <div className="page-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button className="btn btn-ghost btn-sm" onClick={() => setView('list')}>← Back</button>
          <div>
            <div className="page-title">📥 New Receipt</div>
            <div className="page-subtitle">Stock IN from supplier</div>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div className="stepper">
            {['Draft','Ready','Done'].map((s, i) => (
              <span key={s} className={`stepper-step ${i === 0 ? 'active' : ''}`}>
                {i > 0 && <span className="stepper-arrow">›</span>}{s}
              </span>
            ))}
          </div>
          <code style={{ fontSize: 14, fontWeight: 800, color: 'var(--accent-blue)', background: 'rgba(79,142,255,0.1)', padding: '6px 12px', borderRadius: 8 }}>{refNum}</code>
        </div>
      </div>

      {alert && <div className={`alert alert-${alert.type}`}>{alert.msg}</div>}

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 280px', gap: 20 }}>
        <div>
          <div className="card" style={{ marginBottom: 16 }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 16 }}>Receipt Details</div>
            <div className="form-grid">
              <div className="form-group">
                <label className="form-label">Receive From (Supplier)</label>
                <select className="form-select" value={form.supplier_id} onChange={e => setForm({ ...form, supplier_id: e.target.value })}>
                  <option value="">Select supplier</option>
                  {suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">Destination Location *</label>
                <select className="form-select" value={form.to_location} onChange={e => setForm({ ...form, to_location: e.target.value })} required>
                  <option value="">Select location</option>
                  {locations.map(l => <option key={l.id} value={l.id}>{l.warehouse_name} — {l.name}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">Schedule Date</label>
                <input className="form-input" type="date" value={form.scheduleDate} onChange={e => setForm({ ...form, scheduleDate: e.target.value })} />
              </div>
            </div>
          </div>

          <div className="card">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Products</div>
              <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>{validLines.length} item{validLines.length !== 1 ? 's' : ''} · {totalQty} total units</span>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 130px 36px', gap: 8, padding: '6px 0', marginBottom: 4 }}>
              <span style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)' }}>Product</span>
              <span style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)' }}>Quantity</span>
              <span />
            </div>
            {form.lines.map((line, i) => (
              <div key={i} style={{ display: 'grid', gridTemplateColumns: '1fr 130px 36px', gap: 8, marginBottom: 8, alignItems: 'center', padding: '10px 12px', background: 'var(--bg-secondary)', borderRadius: 10, border: '1px solid var(--border)' }}>
                <select className="form-select" style={{ background: 'transparent', border: 'none', padding: '4px 0' }} value={line.product_id} onChange={e => updateLine(i, 'product_id', e.target.value)}>
                  <option value="">Select product</option>
                  {products.map(p => <option key={p.id} value={p.id}>[{p.sku}] {p.name}</option>)}
                </select>
                <input className="form-input" type="number" min="1" placeholder="0" value={line.quantity} onChange={e => updateLine(i, 'quantity', e.target.value)} style={{ textAlign: 'center', fontWeight: 700 }} />
                <button onClick={() => removeLine(i)} disabled={form.lines.length === 1} style={{ background: 'none', border: 'none', color: form.lines.length === 1 ? 'var(--text-muted)' : 'var(--accent-coral)', cursor: form.lines.length === 1 ? 'not-allowed' : 'pointer', fontSize: 18, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>✕</button>
              </div>
            ))}
            <button onClick={addLine} style={{ width: '100%', padding: '10px', background: 'rgba(79,142,255,0.06)', border: '1px dashed var(--accent-blue)', borderRadius: 10, color: 'var(--accent-blue)', cursor: 'pointer', fontSize: 13, fontWeight: 600, marginTop: 4, transition: 'all 0.15s' }}>
              + Add Product Line
            </button>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <div className="card" style={{ background: 'rgba(0,229,160,0.06)', border: '1px solid rgba(0,229,160,0.2)' }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--accent-green)', textTransform: 'uppercase', marginBottom: 12 }}>Summary</div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8, fontSize: 13 }}>
              <span style={{ color: 'var(--text-muted)' }}>Products</span>
              <span style={{ fontWeight: 700 }}>{validLines.length}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8, fontSize: 13 }}>
              <span style={{ color: 'var(--text-muted)' }}>Total Units</span>
              <span style={{ fontWeight: 700, color: 'var(--accent-green)', fontSize: 18 }}>{totalQty}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13 }}>
              <span style={{ color: 'var(--text-muted)' }}>Destination</span>
              <span style={{ fontWeight: 600, fontSize: 12, textAlign: 'right', color: 'var(--text-secondary)' }}>{form.to_location ? locations.find(l => l.id === Number(form.to_location))?.name || '—' : '—'}</span>
            </div>
          </div>

          <button className="btn btn-success" style={{ width: '100%', justifyContent: 'center', padding: '14px', fontSize: 15 }} onClick={handleValidate} disabled={validating || validLines.length === 0 || !form.to_location}>
            {validating ? <><div className="spinner" style={{ width: 16, height: 16 }} /> Validating...</> : '✅ Validate Receipt'}
          </button>
          <button className="btn btn-ghost" style={{ width: '100%', justifyContent: 'center' }} onClick={handlePrint}>🖨️ Print Receipt</button>
          <button className="btn btn-ghost" style={{ width: '100%', justifyContent: 'center' }} onClick={() => setView('list')}>✕ Cancel</button>
        </div>
      </div>
    </div>
  );

  return (
    <div>
      <div className="page-header">
        <div>
          <div className="page-title">📥 Receipts</div>
          <div className="page-subtitle">{receipts.length} receipts · Stock IN operations</div>
        </div>
        <button className="btn btn-primary" onClick={() => setView('new')}>+ New Receipt</button>
      </div>

      {alert && <div className={`alert alert-${alert.type}`}>{alert.msg}</div>}

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 14, marginBottom: 24 }}>
        <div className="kpi-card green"><div className="kpi-icon">📥</div><div className="kpi-label">Total Receipts</div><div className="kpi-value">{receipts.length}</div></div>
        <div className="kpi-card blue"><div className="kpi-icon">📦</div><div className="kpi-label">Units Received</div><div className="kpi-value">{receipts.reduce((s, m) => s + m.quantity, 0)}</div></div>
        <div className="kpi-card purple"><div className="kpi-icon">🏭</div><div className="kpi-label">Suppliers</div><div className="kpi-value">{suppliers.length}</div></div>
      </div>

      <div className="search-bar">
        <span>🔍</span>
        <input placeholder="Search by reference or product..." value={search} onChange={e => setSearch(e.target.value)} />
        {search && <button onClick={() => setSearch('')} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}>✕</button>}
      </div>

      <div className="table-wrap">
        {loading ? <div className="loading"><div className="spinner" />Loading...</div>
        : filtered.length === 0 ? (
          <div className="empty-state">
            <div className="empty-state-icon">📥</div>
            <div className="empty-state-text">No receipts yet — click New Receipt to create one</div>
          </div>
        ) : (
          <table>
            <thead><tr><th>Reference</th><th>Product</th><th>Destination</th><th>Qty</th><th>Date</th><th>Status</th></tr></thead>
            <tbody>
              {filtered.map(m => (
                <tr key={m.id} className="row-in">
                  <td><code style={{ fontSize: 12, color: 'var(--accent-blue)', fontWeight: 700 }}>{m.reference}</code></td>
                  <td className="td-main">{m.product_name} <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>({m.sku})</span></td>
                  <td style={{ color: 'var(--text-secondary)' }}>{m.to_location_name || '—'}</td>
                  <td><span style={{ fontWeight: 700, color: 'var(--accent-green)', fontSize: 15 }}>+{m.quantity}</span></td>
                  <td style={{ color: 'var(--text-muted)', fontSize: 12 }}>{m.operation_date ? new Date(m.operation_date).toLocaleDateString() : '—'}</td>
                  <td><span className="badge badge-green">✅ Done</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
